# Generated by Django 4.0.4 on 2022-05-08 09:43

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=255, unique_for_date='created_on')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('partial_day',
                 models.CharField(choices=[('AM', 'Buổi sáng'), ('PM', 'Buổi chiều'), ('ALL', 'Cả ngày')],
                                  default='ALL', max_length=3)),
                ('detail_reason', models.TextField(blank=True, null=True)),
                ('expected_approve', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('approver',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_approver',
                                   to=settings.AUTH_USER_MODEL)),
                ('inform_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='request_inform_to', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_owner',
                                            to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tms.reason')),
                ('request_type',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tms.requesttype')),
                ('supervisor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_supervisor',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
